<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class MarkerRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [
//            'event_id' => 'required',
            'sanitary_id' => 'required',
//            'type_id' => 'required',
//            'category_id' => 'required',
            'height' => 'required',
            'diameter' => 'required',
            'breed_id' => 'required',
            'landing_date' => 'nullable',
//            'age' => 'required',
            'status_id' => 'nullable',
            'geocode' => ["required","array","min:1","max:21"]
        ];
    }

    public function attributes()
    {
        return [
            'event_id' => 'хозяйственное мероприятие',
            'sanitary_id' => 'состояние',
            'type_id' => 'вид насаждения',
            'height' => 'высота',
            'diameter' => 'диаметр',
            'breed_id' => 'порода',
            'geocode' => 'маркер',
            'age' => 'возраст'
        ]; // TODO: Change the autogenerated stub
    }
}
